spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hms
    username: root
    password: S@NKITA123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  algorithm:
    key: akdhauidyasballeyasbdchuasfhbvkjsadsajchsadhjcsd
  issuer: Ankit
  expiry:
    duration: 86400000